// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Store.Data;

#nullable disable

namespace Store.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    partial class ProductDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Store.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryName")
                        .IsUnique();

                    b.HasIndex("Id");

                    b.ToTable("Category", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "İç Giyim"
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "Dış Giyim"
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "Kışlık"
                        },
                        new
                        {
                            Id = 4,
                            CategoryName = "Spor"
                        },
                        new
                        {
                            Id = 5,
                            CategoryName = "Şapka"
                        },
                        new
                        {
                            Id = 6,
                            CategoryName = "Ayakkabı"
                        },
                        new
                        {
                            Id = 7,
                            CategoryName = "Terlik"
                        });
                });

            modelBuilder.Entity("Store.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(700)
                        .HasColumnType("nvarchar(700)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Id");

                    b.HasIndex("Name");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 2,
                            Description = "Mavi Jeans",
                            Name = "Pantolon",
                            Price = 1200m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Description = "Mavi Düğmeli",
                            Name = "Gömlek",
                            Price = 1000m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 5,
                            Description = "Kırmızı, Tüylü",
                            Name = "Bere",
                            Price = 200m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "Beyaz",
                            Name = "Atlet",
                            Price = 50m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Description = "Siyah",
                            Name = "Boxer",
                            Price = 40m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            Description = "Siyah, Kaz Tüylü",
                            Name = "Mont",
                            Price = 1700m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 7,
                            Description = "Mavi, Tuvalet Terliği",
                            Name = "Sandalet",
                            Price = 25m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 4,
                            Description = "Siyah, Lastikli",
                            Name = "Spor Bandı",
                            Price = 220m
                        });
                });

            modelBuilder.Entity("Store.Models.Product", b =>
                {
                    b.HasOne("Store.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Store.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
